services:
  postgres:
    image: postgres:15.2-alpine
    container_name: c-postgres-bsn
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_book_social_network
      POSTGRES_USER: magadiflo
      POSTGRES_PASSWORD: magadiflo
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U magadiflo -d db_book_social_network' ]
      interval: 10s
      timeout: 5s
      retries: 5

  mail-dev:
    image: maildev/maildev
    container_name: c-mail-dev-bsn
    restart: unless-stopped
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-net

  book-network-backend:
    image: magadiflo/book-network-backend:1.0.0
    container_name: c-book-network-backend
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - spring-net
    depends_on:
      postgres:
        condition: service_healthy

  book-network-frontend:
    image: magadiflo/book-network-frontend:1.0.0
    container_name: c-book-network-frontend
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - spring-net

volumes:
  postgres_data:
    name: postgres_data

networks:
  spring-net:
    name: spring-net