server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: book-network-backend

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json
