spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/db_book_social_network
    username: magadiflo
    password: magadiflo

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: magadiflo@gmail.com
    password: vzpopostwaqgsljr
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org.hibernate.SQL: DEBUG

application:
  security:
    jwt:
      secret-key: jNFY9S0YoLZ9xizq2V8FG5yMudcZpBKXyLQjSWPbiX8jNFY9S0Y
      expiration: 3600000
  mailing:
    frontend:
      activation-url: http://localhost:4200/auth/activate-account
  file:
    upload:
      photos-output-path: ./uploads